(defun org-roam-ui-export ()
  "Export `org-roam-ui's-data for usage as static webserver."
  (let* ((dir (read-file-name "org-roam-ui-export"))
        (graphdata-file (concat (file-name-as-directory dir) "graphdata.json"))
        (notes-dir (concat (file-name-as-directory dir) "notes/")))
    (org-roam-ui--export-graphdata graphdata-file)
    (make-directory notes-dir :parents)
    (mapcar (lambda (id)
              (let* ((cid (car id))
                     (content (org-roam-ui--get-text cid)))
                (write-region content nil (concat notes-dir cid) 'append)))
            (org-roam-db-query "select id from nodes;"))))
