:PROPERTIES:
:ID:       543414ce-fd12-470b-a38a-c61cfc10bfe4
:ROAM_ALIASES: IE
:END:
#+title: Information Extraction
#+filetags: :nlp:ai:

see [[id:68c96f44-815a-4607-8149-ba49f3b5b00d][Practical NLP (book)]]

* Misc
 - extracting relevant information (structured query-response pair) from a given text (unstructured data)
 - is a relatively complex task than classification and requires further preprocessing/more complicated representations (part of speech tagging for instance) than just getting away with treating text as tokens.
 - a different pipeline may need to be employed dependent on how the knowledge base is structured - queryable knowledge bases have to be treated differently than a collection of documents without much metadata.
* Applications
 - Tagging news and other content -> topic recognization by search engines for quick displays.
 - Chatbots -> understanding references to entities in a conversation, and understanding their nature (location, person, etc) to be able to respond appropriately.
 - Social media monitoring : evolution of an event related to specific topic aka crowd sourcing potential news.
 - processing structured documents (forms and receipts) : [[id:e86025e5-e316-4c83-88a4-a2a341e72550][OCR]] + [[id:20230713T150554.400026][NLP]]

* Tasks in IE
The simpler ones can be categorized into the below. Complex combinations of the following/spinoffs thereoff will be explored in dedicated nodes.
** Key Phrase Extraction (KPE)
:PROPERTIES:
:ID:       898ce1bb-cbe9-4358-97b8-f5f2bc3f8d83
:END:
** Named Entity Recognition (NER)
:PROPERTIES:
:ID:       71a53540-e823-49a2-9049-b286ee265e62
:END:
** Named Entity Disambiguation and Linking
:PROPERTIES:
:ID:       01cef446-e7e0-48f6-af7b-d0478e689cf2
:END:
** Relation Extraction
:PROPERTIES:
:ID:       2f0bed79-b0cd-4c70-88a2-d219ab174db9
:END:
** Temporal Information Ixtraction
:PROPERTIES:
:ID:       8731f087-2ee8-4b2e-98c8-de52c78dc399
:END:
** Template Filling
* Generic IE Pipeline
:PROPERTIES:
:ID:       c20845f9-d217-4a73-956a-4aebde564c59
:END:
