:PROPERTIES:
:ID:       825d36cc-4e03-48e5-bca8-0845e51090af
:END:
#+title: The Meta-Subject
#+filetags: :meta:

* Abstract Node Seed
Check out this seeding read to get started and what the lay of the land is for forming novel terminologies: https://press.princeton.edu/books/hardcover/9780691171982/the-evolution-of-knowledge

I think I'm the right guy to map out the root of knowledge as it exists today. Thinking of going back to how vernacular stuff propogated and how research is conducted today...

Would be a long timeline of branches that probably originate from one root that leads to what we know about the world today.

There'll be a lot of definitions that I'll need to build up to describe subjects and their domains...

The Meta-Subject. I could really draw from some data representation concepts to really build this behemoth of a book. Could be my life's work.
The Subjects that tries collecting all subjects under one umbrella and view all of knowledge from a flexible and non-restraining but structured hierarchical framework.

All starts with learning the roots of all knowledge and backtracking to the beginnings of recorded usage of knowledge before I can start building up a tree.
I'll definitely need a data structure for the same that I can improve upon over time.

I'll be proceeding with common lisp.

* Experimental Notions
I'm testing these out in this brain dump and will be incorporating these into a formal theory upon accumulating multiple successful applications.
** The Idea of Diffing Domains
:PROPERTIES:
:ID:       b68a599a-b800-47c9-b299-a9535d23daf5
:END:
 - when trying to explain the difference between epistemology and ontology, I came up with the idea of qualitatlively applying [[id:e6c6918c-25bd-47f4-830a-4221452885e8][IOU]].
 - now I can say that
#+begin_src 
IOU(objectivist epistemology, ontology) > IOU(epistemology, ontology)
#+end_src

** Degrees of Freedom : Cartesianization
:PROPERTIES:
:ID:       d0d75b64-13e5-4b50-8833-a2b6a47cdf19
:END:
One can factorize a complex domain into its constituent abstractions by identifying the separate degrees of freedom in its description. Varying the extent of a particular degree at a time allows one to meaningfully study variants rather than simply diffing domains.
