:PROPERTIES:
:ID:       20230712T131112.909632
:ROAM_ALIASES: blog
:END:
#+title: Writing
#+filetags: :meta:transient:

root blog : https://rajpatil.dev
medium : https://rajp152k.medium.com/
* Comment stream
** 0x21D1
Also starting out writing on medium : will be adapting all blogs to medium to help bring in traffic to the root site.
 - read some blogs on medium and finding some styles to be easy to be able to follow.
 - writing longer sentences doesn't help with comprehension and leads to constriction of the flow of ideas for the reader.
 - writing monotonically crafted sentences also isn't helpful for engagement
 - instead, should try a periodic strategy that helps build up the article programmatically.
 - varying sentence length, complexity and specificity over a paragraph moving from generic to specific to build up on the previous layer is something that I'll be trying out in the coming blogs.
 - should keep the paragraphs shorter, use more subheadings and break down the flow of the blog into several sections that allows for skimming as well.
   - I personally miss on these in long worded blogs and do not like to read paragraph after paragraph without an explicit indication of what I'm looking at currently.
 - when it comes to planning an article, there are a few repeating factors that one should take into account.
   - Simplifying extensively, there's the characteristics of the content itself, then there're the characteristics of the reader and finally the interaction of these characteristics over time and how engagement grows. Lastly, these may broken down into implicit factors like the content being a realization of the characteristics of the author.
   - All writing and content creation recommendations play on variations in these factors and any specific suggestions may be boiled down to how these can be varied to achieve certain objectives.
   - This can be summarized as a game of incentives : the content captures the incentive of the author and may be consumed by the consumer if the incentives align well.
 - This deserves to be a subject of it's own and has been further documented in the node of [[id:20240114T175025.020370][Content Theory]]
** 0x21A6
 - I'm considering being more concise
 - Being verbose is a style that I exhibit naturally but I have noticed that my words are the most impactful when I'm concise and only type after considerable thought.
 - both have their times of prominence but I don't think I practice the former enough due to the skewed nature of the effort I put in this dump versus the original blog.
** 0x21A3 
 - I thought I'd reached 0x2200, but I forgot stuff is in hex here.
 - have been able to bring a healthy level of monotony in my routines (read smooth highways without speed bumps and ditches)
 - writing in Emacs and coding in Neovim so that's working pretty well.
 - forcing a routine on writing henceforth: not just something I do according to my whims but something that is a disciplined endeavour henceforth.
** 0x216A
 - on a post shower, night walk with music, was able to brain storm several core bloggable prompts
 - hadn't been able to do so in a long time and definitely felt satisfied by the end of it
 - I was missing my small paper notes and realized that I've got to get used to the phone and get over my peeve against complex instruments for writing.
 - will still be using the work in progress subnode here to capture these prompts in batches
** 0x215D
- reading a book on prompt engineering to actively improve my content creation process - had a pretty productive chat as follows : https://chat.openai.com/share/6896002b-08bc-4e85-af48-82bbffc4f5cd
** 0x2148
 - elaborating on the book that I mentioned yesterday, found this interesting strategy on writing a book
   - to publish it in atomic parts with each fundamental idea being a blog post.
   - this way I get intermittent feedback instead of a final review and don't have to deal with the stress of not producing any output.
   - over time, as my style develops, I could even reiterate over old blogs and compile them into the book, refactored and freshened up a little.
 - inspiration : derek sivers and seth godin
** 0x2147
 - writing a book -> [[id:20230827T153308.339339][The Definitive Guide to Books]] 
 - should be a good experience when starting out
 - there has to be a first someday
 - will be completing it in this dump itself and plan on finding out what it takes to actually write a book
 - estimated it to take around 90 hours of work.
** 0x2141
 - setting up a new content creation pipeline video and blog that covers how I note ideas from end to end.
   - the tool-agnostic part is already covered in 0x2118 below.
   - Will be quickly highlighting the tooling and the technical process in a video and then blog about references and links.
 - practical aspects :
   - begin with the buffer
     - contains all my notes
       - for writing
       - what I study
       - for youtube
     - daily increments
       - input and output queue.
   - main blog
     - hugo
     - write in markdown
     - publish with github pages
   - youtube
     - the normal process
       - youtube and blog go hand in hand
** 0x2129
 - [[id:20230730T172240.071698][writing-patterns]]
 - initializing a new node to observe my writing style and its short-comings/opportunities to improve on.
 - would just be a collection of high level patterns that I tend to over-use/rely on unnecessarily and could use some explicit auditing.
** 0x211C
I'm thinking of developing a personalized writing system that will allow me to be disciplined, elevating myself from the stature of a hobbyist. For definite practice, I'm thinking of deciding on a topic at the start of a week, reading up and collating my notes until Saturday and posting the formal article on Sunday.
My goal with this pursuit is to improve my command over the language and develop an original way with word. All communication boils down to being able to express yourself accurately without erroneous comprehension for the audience. That is a skill worth mastering. 
** 0x2118
*** Abstract
**** The Process of Writing

Maintaining a good writing pipeline is essential to automate the process of generating content. In my past endeavours, the process involved the phases of :
 - planning
 - drafting
 - editing
 - posting

This linear process fails to capture how a writer might really think when formulating prose. One would like having convenient access to past works for relevant links and editing is not really a one-and-done job but an iterative process...

Moreover, this makes blogging a versioned process, rather than a living, breathing organism that closely follows your thoughts, symbolically waxing and waning over time, simultaneously growing as a whole.

This also makes you believe that each post is an independent project in itself and discourages linkages with existing works.

I intend to improve upon this process with this setup of decoupling my notes and what I publish.

**** The Incentive to Write 

I have two major objectives (implicitly interdependent) associated with my online presence on the main [[https://rajpatil.dev][blog]] and the [[https://buffer.rajpatil.dev][buffer]]:
 - To write for myself
 - To write for others

Both are important aspects towards being good writer and need to be independently catered to so as to not deter my proficiency in the other.
   
The [[id:20230712T211919.917191][buffer]]s will be a personal brain dump where I won't care about formalizing my notes and any other necessities of published works.They will be shorter and linked to other buffers.
The main [[https://buffer.rajpatil.dev][blog]] will be a formalized projection of multiple inter-related buffers into one serialized output : a snapshot of the living, breathing organism that I intend the buffers to evolve into.
   
*** The Technicalities
  - The main blog is maintained in markdown and published via Hugo
  - The buffers are maintained in org-roam and published via ox-html
    - credits: https://github.com/maker2413/OrgRoamPublish
 Buffer
** Work in Progress
*** Towards Effortless Awareness (documentation)
** Prompts
*** A child's curiosity and an adult's resolve 
 - Curiosity and Focus don't really get together well if you think about it.
 - The first, you're naturally born with and you may have to work on not losing it over time.
 - The latter, you have to build up over your life if you wish to achieve anything of value.
 - Both are necessary for contributing something important to the world
   - although execution (result of focus) might be considered the harder ordeal, creative ideation (result of curiosity) can't be ignored and makes the outcome's potential ingenuity worth the efforts.
*** Care enough to be selectively ignorant
*** Epistemological cartography
*** Don't have role models but target specific characteristics
*** Video Games, Lucidity and L-theanine
*** Epistemological Voraciousness
*** Ingredients of Originality
 - fearlessness, especially of being perceived as stupid definitely takes the cake
*** Feigning humility
*** On the boundaries of madness and brilliance
*** Embrace abstracted Complexity : simplicity is overrated
*** Can you defend your beliefs?
*** Introductory Self hypnosis
*** Tactics, principles and strategy
*** when to pluck low hanging fruits
*** Convergence
*** Embracing the Suck: boredom, adulthood and expectations from your days
*** Cyber Transparency : How much is enough or too much : is there an optimal amount?
