:PROPERTIES:
:ID:       20230713T110006.406161
:END:
#+title: Machine Learning
#+filetags: :root:transient:

This node captures misc info[[id:20230713T110006.406161][Machine Learning]]rmation regarding the large root that ML is.
I plan on accumulating and assimilating all that I learn from various domains in a uniform manner here. It'll be notebooks from completed [[id:f275e17f-307e-4e2b-a67b-6511774d0a3d][kaggle]] competitions, blogs, papers, courses, anything that's worth goes in. I don't plan on incorporating complete book walkthroughs in here - I'll reference them and won't be mapping what I read verbatim. [[id:9539ffd2-433b-4cac-babc-0d45990a4642][Wikipedia]] is a good quick reference so will be referencing that too rather than typing what's within convenient reach.

* Competition Analysis Indexes
** https://www.kaggle.com/competitions/icr-identify-age-related-conditions


* Misc nodes
** No Free Lunch
 - no model is better at all problems than all other models
** [[id:51c4a1c3-9289-4f09-bb95-1585b750f328][Occam's Razor]]
 - on why traditional machine learning methods are still relevant with [[id:20230713T110040.814546][Deep Learning]] on the rise.
** [[id:398d134d-6193-409a-b3b5-9e7c7de86ce7][Interpretable ML]]
 - ML models are generally a black box that are inexplicable representations of the data they are trained on.
 - understanding how a model favors certain outputs for a set of input features is a domain in itself.


* Sentinels 
** SpaCy
:PROPERTIES:
:ID:       68e44f89-7d87-4ac6-9c00-f6ba3c38257d
:END:
 - Industrial grade NLP tooling
** TextaCy
:PROPERTIES:
:ID:       3fba4bcf-cf1d-491e-b847-71b08c86080f
:END:
 - built on top of [[id:68e44f89-7d87-4ac6-9c00-f6ba3c38257d][Spacy]] for more specific nlp tasks
   -> see [[id:543414ce-fd12-470b-a38a-c61cfc10bfe4][Information Extraction]] for instance

** DisplaCy
:PROPERTIES:
:ID:       a784e58a-e9f9-438c-b93d-d1995a2fb184
:END:
 - a visualizer by explosion.ai
 - used during [[id:71a53540-e823-49a2-9049-b286ee265e62][Named Entity Recognition (NER)]]
