:PROPERTIES:
:ID:       20230809T042334.724258
:END:
#+title: philosophy
#+filetags: :root:

Espistemologically : The love of wisdom..  

Love and wisdom are themeselves something that I can't define nor understand completely.
Without them, how can I expect to understand philosophy. Albeit, I still throw around that word a lot and to the best of my knowledge, it mostly isn't employed in the right sense depending on the situation.

Irrespectively, continuing with whatever broken implicit connotation my mind harbors for these words...

I wouldn't say I love wisdom: I would rather say that I find it useful. Philosophy (straying away from the epistemology henceforth) is something that I find useful in situations that demand a more well-thought out response, where the reptilian course of action may lead to irreparable damage and/or lost time...  

The idea of reading philosophical texts is different than that of practicing what you read. During my difficult times, recalling all that I've read and collating all that suited the current situation wasn't that easy. Emotions are real and controlling them in difficult times is definitely not an easy endeavor. I don't emote that often, nor do I think I can fake an emotion (I think I'm good at figuring out when others are faking an emotion though).

Most of the time, I come off as an apathetic but I can assure I'm not one (a large, expression-masking beard doesn't help the case either). I wouldn't say I'm a very good empath either. I mention all of this because being philosophical and emoting oneself freely are, I believe, intrinsically antagonistic states of being.

Being perceived as tense and pissed-off is more often the norm due to my resting face, and I have to invest considerable efforts to not be seen as unwelcoming (I believe I'm welcoming) to a conversation. 

Anyway, backtracking from that emotional tangent, 
