:PROPERTIES:
:ID:       20230712T131112.909632
:ROAM_ALIASES: blog
:END:
#+title: Writing
#+filetags: :transient:

* Comment stream
** 0x215D
 - reading a book on prompt engineering to actively improve my content creation process
   - had a pretty productive chat as follows : https://chat.openai.com/share/6896002b-08bc-4e85-af48-82bbffc4f5cd
** 0x2148
 - elaborating on the book that I mentioned yesterday, found this interesting strategy on writing a book
   - to publish it in atomic parts with each fundamental idea being a blog post.
   - this way I get intermittent feedback instead of a final review and don't have to deal with the stress of not producing any output.
   - over time, as my style develops, I could even reiterate over old blogs and compile them into the book, refactored and freshened up a little.
 - inspiration : derek sivers and seth godin
** 0x2147
 - writing a book -> [[id:20230827T153308.339339][The Definitive Guide to Books]] 
 - should be a good experience when starting out
 - there has to be a first someday
 - will be completing it in this dump itself and plan on finding out what it takes to actually write a book
 - estimated it to take around 90 hours of work.
** 0x2141
 - setting up a new content creation pipeline video and blog that covers how I note ideas from end to end.
   - the tool-agnostic part is already covered in 0x2118 below.
   - Will be quickly highlighting the tooling and the technical process in a video and then blog about references and links.
 - practical aspects :
   - begin with the buffer
     - contains all my notes
       - for writing
       - what I study
       - for youtube
     - daily increments
       - input and output queue.
   - main blog
     - hugo
     - write in markdown
     - publish with github pages
   - youtube
     - the normal process
       - youtube and blog go hand in hand
** 0x2129
 - [[id:20230730T172240.071698][writing-patterns]]
 - initializing a new node to observe my writing style and its short-comings/opportunities to improve on.
 - would just be a collection of high level patterns that I tend to over-use/rely on unnecessarily and could use some explicit auditing.
** 0x211C
I'm thinking of developing a personalized writing system that will allow me to be disciplined, elevating myself from the stature of a hobbyist. For definite practice, I'm thinking of deciding on a topic at the start of a week, reading up and collating my notes until Saturday and posting the formal article on Sunday.
My goal with this pursuit is to improve my command over the language and develop an original way with word. All communication boils down to being able to express yourself accurately without erroneous comprehension for the audience. That is a skill worth mastering. 
** 0x2118
*** Abstract
**** The Process of Writing

Maintaining a good writing pipeline is essential to automate the process of generating content. In my past endeavours, the process involved the phases of :
 - planning
 - drafting
 - editing
 - posting

This linear process fails to capture how a writer might really think when formulating prose. One would like having convenient access to past works for relevant links and editing is not really a one-and-done job but an iterative process...

Moreover, this makes blogging a versioned process, rather than a living, breathing organism that closely follows your thoughts, symbolically waxing and waning over time, simultaneously growing as a whole.

This also makes you believe that each post is an independent project in itself and discourages linkages with existing works.

I intend to improve upon this process with this setup of decoupling my notes and what I publish.

**** The Incentive to Write 

I have two major objectives (implicitly interdependent) associated with my online presence on the main [[https://rajpatil.dev][blog]] and the [[https://buffer.rajpatil.dev][buffer]]:
 - To write for myself
 - To write for others

Both are important aspects towards being good writer and need to be independently catered to so as to not deter my proficiency in the other.
   
The [[id:20230712T211919.917191][buffer]]s will be a personal brain dump where I won't care about formalizing my notes and any other necessities of published works.They will be shorter and linked to other buffers.
The main [[https://buffer.rajpatil.dev][blog]] will be a formalized projection of multiple inter-related buffers into one serialized output : a snapshot of the living, breathing organism that I intend the buffers to evolve into.
   
*** The Technicalities
  - The main blog is maintained in markdown and published via Hugo
  - The buffers are maintained in org-roam and published via ox-html
    - credits: https://github.com/maker2413/OrgRoamPublish

* Production
An index of all that I write about, published, work in progress and prospective.
** Published
|------------+-----------------------------------------------------------+----------------------------------------------------------------+-----------|
| time index | Production code name                                      | link                                                           | Category  |
|------------+-----------------------------------------------------------+----------------------------------------------------------------+-----------|
|     0x215E | Prompt crafting distilled                                 | https://rajpatil.dev/post/dense-guide-prompt-engineering/      | Skills    |
|     0x215E | I have a Writing Tutor now ...                            | https://rajpatil.dev/post/better-writer/                       | Writing   |
|     0x215B | Do you really wanna be a Polymath?                        | https://rajpatil.dev/post/aefraisk/                            | Polymathy |
|     0x215B | The Polymathic Gamble                                     | https://rajpatil.dev/post/polymathy/                           | Polymathy |
|     0x214F | Reading an Author                                         | https://rajpatil.dev/post/reading-an-author/                   | Anecdote  |
|     0x214F | Refactoring Old Works                                     | https://rajpatil.dev/post/refactoring-old-works/               | Writing   |
|     0x214C | The Definitive Guide to Books                             | https://rajpatil.dev/post/the-definitive-guide-to-books/       | Writing   |
|     0x2147 | Practical Natural Language Processing : C1 - 5            | [[https://rajpatil.dev/post/practical-nlp-c1-5/]]                  | Book      |
|     0x2147 | Common Lisp : The Series - 0.1 : Representing Programs    | https://rajpatil.dev/post/clts/clts-0.1/                       | CLTS      |
|     0x2141 | My Creation and Publishing Pipeline                       | https://rajpatil.dev/post/my-creation-and-publishing-pipeline/ | Writing   |
|     0x213F | Common Lisp: The Series - 0 : Introduction                | https://rajpatil.dev/post/clts/clts-0/                         | CLTS      |
|     0x213B | RIP, Bram Moolenar                                        | https://rajpatil.dev/post/rip-bram-moolenar/                   | Tribute   |
|     0x213B | My Emacs Configuration                                    | https://rajpatil.dev/post/my-emacs-config-0x213b/              | Configs   |
|     0x213A | Common Lisp - Gentle Introduction to Symbolic Computation | https://rajpatil.dev/post/cl-aitsc/                            | Book      |
|     0x212B | PICC: pragmatics of intellectual consumption and creation | https://rajpatil.dev/post/picc/                                | Skills    |
|     0x211B | Here we go again...                                       | https://rajpatil.dev/post/writing-setup/                       | Writing   |
|------------+-----------------------------------------------------------+----------------------------------------------------------------+-----------|

** Work in Progress
*** Who are you?
 - was reading my old blog the other day and I just recollected a whole bunch of memories based on who I was as a person.
 - Life isn't a markov process.
   - the future isn't only dependent on your present.
   - it depends on how you interact with your environment.
     - in my case : that was reading my old blogs and watching my old videos
     - I'm essentially carrying my past self's thoughts and wisdom into the present when I create any content.
   - My present state which is not just my accessible memories anymore but my blog, my videos and humans that know me and my past and can sustain a conversation about it keeps on growing
   - Creating is an act of making your present state more comprehensive : by accumulating your past into a large stream of actions, logs, decisions.
 - You (assuming you can be represented by an artificially intelligent algorithm) are bound to consolidate your life better to better decide for your future decisions if you have more data accessible to you.
 - this data can be:
   - generic or specific
   - statistical or rule-based
 - Generic data can only take you so far.
 - Unless you put in the effort to know who "you" really are, your "algorithms" will only generate generic advice and probably won't yield the best possible results.
 - creating content is a form of capturing snapshots of your past present states that can be studied on demand later on to more accurately represent your path to the present.
 - Now, the past, isn't actually changable even if you change the way you think about it.
   - there's the objective past (questionable what's objective) (an event that's one and done) and then there's your perspective about it (that is a stream that you carry on for life (I'm not accounting for forgetting right now if you journal, blog, create any sort of sensible content as it is easily accessible : (example : I could remember what stage of Life I was in based on the book that I was reading then : Once I saw the book : All memories fell into context like dominoes))).
   - you can only alter your perspective about the past in the present moment of the stream but never change your previous thoughts in the stream.
   - There is no mental time machine allowing you to manipulate your past memories : you simply partially overwrite stuff but never alter it's state in the past...
 - thinking of how I could structure these posts : the future also plays a part in making decisions - there is some level of certainty associated with the future if you chalk out your actions and have realistic expectations out of them.
   - being in a definite caloric deficit while following an recordable resistance training protocol will yield results that will be within a certain definite range around your expectations when you set out with the goal.
** Prospective
*** Filler skills
 - juggling
 - miscellaneous push ups throughout breaks
 - reading
 - meditative walks
 - mental games -> structuring an article mentally given a writing prompt is a pretty complex and satisfying mental game
 - if you're a physics aficionado like I am, consider observing your surroundings and coming up with mental mathematical models to represent reality.
*** Why text is awesome (for logicians.) and semantically discrete images is what you should limit yourself to
