:PROPERTIES:
:ID:       20230827T153308.339339
:END:
#+title: A Pragmatist's Guide to Literature
#+filetags: :book:

* Readings
** Articles
 - [[https://en.wikipedia.org/wiki/What_Is_Literature%3F][What Is Literature? - Wikipedia]]
 - https://oer.pressbooks.pub/theworryfreewriter/chapter/introduction-to-literature/
** Books
* Planning stream
** 0x2233
 - This is going to be the definitive guide to books
 - I'll be starting with a base assumption as to what are books
 - Assuming you're an alien and need a complete introduction as to how books work.
 - This in turn should help me understand and breakdown all the relevant concepts about content creation
 - I'd already been reading and writing about writing in general and would like to actually speed up the whole process of writing a book.
 - will be publishing this as free of cost (might just do it for all the books that I write in the initial phase of my career)
 - plan on learning the nuances that need to be taken care of when it comes to understanding a domain and writing a book about it.
 - starting from scratch: archiving out all the old content into the archivals.
 - checkout [[id:20240421T173425.305252][Literature]]
* Content Stream
** 0x2233
 - Jean Paul Sartre in his Essays talks about Prose and Poetry and their differences : [[https://en.wikipedia.org/wiki/What_Is_Literature%3F][What Is Literature? - Wikipedia]]
* Archivals
** Structure and Content
*** Introduction
**** Why am I writing this book?
***** Personal reading journey
Began at 19 with a technical inclination and hardly ready a book other than something that my curriculum demanded. Over 3 years, read 13 , 41 and 54 books respectively ranging from ....
- My background with reading books -> initial philosophical blog
- University was the first time I had time to spare for pursuing hobbies in a balanced manner with independence.
- I only used to read technically
**** Who is this book for?
***** reading experience
- ones who wish to start reading
- monolithic readers
- voracious readers who wish to pump their egos
*** Abstract
**** Associated blogs
**** Why Read
***** An intricate and comparatively (to photos, videos, etc) potent index into your past :- your time now, in hindsight, will seem denser.
- depending on what phase of life you read a book in, revisiting your reviews later on will help you recall smaller details that no other media can compare to...
- stack that into a stream of timestamped reviews and you have a backdoor to your memories so powerful that you can recite the evolution of your intellectual state over that period of time.
***** Cognitive Benefits
- can formulate yourself effectively and conversations won't fizzle out because you will be relevant.
***** Emotional and Intellectual Maturity
***** Social Benefits 
- Access to eccentric and interesting communities
- sustaining a conversation : you may rightfully begin hating small talk
*** Pragmatics
**** Associated blogs
- [ ] Being a sneaky reader
- [X] https://rajpatil.dev/post/hunt-feast-repeat/
- [X] https://rajpatil.dev/post/writing-setup/
- [X] https://rajpatil.dev/post/picc/
**** what should you read : the joy of reading diversely
- On idea hunts and ideation feasts
**** Choosing your next book
**** Making reading a part of your life
**** Making the habit stick
**** Fixating on techniques and tools
**** Consolidating what you read : reviews, blogs, videos.
**** That One Book...
- The one that hits all the right sweet spots right.
  - you find it at the right phase of your life just when you needed to get into that particular thing and needed inspiration for that one particular thing
- Leonardo Da Vinci's Biography for Walter Isaacson did it for me
**** Overcoming Reading Slumps
*** Writing Books
**** Associated blogs
- [X] https://rajpatil.dev/post/my-creation-and-publishing-pipeline/
- [X] https://rajpatil.dev/post/most-important-book/                 
- [X] https://rajpatil.dev/post/better-writer/
- [X] https://rajpatil.dev/post/dense-guide-prompt-engineering/
**** Stepping stones
**** Choosing your topic
**** Why write?
*** Conclusion
- books are not the way to explore the universe
- they're definitely a ticket to the insights that'll help you do so

** Archived Planning Stream
*** 0x216A
indexing a blog entry into the book's content: https://rajpatil.dev/post/most-important-book/
- goes in the latter half of the book (on writing books)
*** 0x2146
- started my morning with 20 mins of mental warm up, listening to a relevant podcast, while juggling and some pushups and squats sprinkled in ...
  - am definitely awake without my daily caffeine cognitive kick-starter; yet to see how my workouts will be given this is the first day of going caffeine free.
*** 0x2141
- was thinking of a blog post on how to go about choosing your next book but this is a great opportunity to write a book on everything that is to figure out about books. Given that my best reading spree resulted in consuming 100+ diverse books over a span of two years. I can elaborate pretty well upon how reading can change your life for the better forever change the way you operate.
- Planning for this to be "the" guide for humans that want to read diversely -> From Dante's Divine Comedy to Da-vinci's codices ..
- some basic tissue paper math, for the number of hours I need to invest..

  ------------
  
#+begin_src lisp  :exports both
  (let ((words-per-line 15)
        (lines-per-page 20)
        (expected-pages 200)
        (expected-words-per-hour 500)
        (excess-frac 1.5)
        (self-confidence 2))
    (/ (* words-per-line lines-per-page expected-pages excess-frac)
       (* expected-words-per-hour self-confidence)))
#+end_src

#+RESULTS:
: 90.0

... hours of effort needed.

-------------

- will be writing it in the brain dump in different notes 

