:PROPERTIES:
:ID:       20231111T232750.075460
:END:
#+title: Polymathy
#+filetags: :skills:

I've read quite a bit about being a modern renaissance man and I've decided I'm going to pursue several domains to keep my life interesting.

* The Intellectual Super-Villain's Reading List

Reading diversely is an integral part of such an endeavor. Given my Anti-Hero (I'm not a super-villain.., yet.) inclinations.. I'm creating a reading list that keeps my exploration directed and disciplined in terms of what I'd like to know.

The following are collations I intend to assimilate into my epistemological arsenal. 

Note that these should be treated as foundational reads. Always supplement with core textbooks from a specialist later down the lane.
Without conveying importance by the order, consider reading: [[id:e8c0b214-fa70-4462-8d44-ae0282d14981][The List]]

* Revamp - The [[id:20240331T194014.871204][IKN0Xes]]

I have been an aspiring polymath for a quite a while and plan on levelling up my engagement with the idea of being competent in several domains.

Being shy of talking about polymathy just becuase you're not the domain expert out of a subset of domains is not in the spirit of things and avoids true insight - conventional paths to acheive domain expertise will not work for me and just can't put in 10,000 hours for silo'd off domain that I wish to master.

I will most definitely have to master and investigate my own personal way of learning things and might even have to redefine what learning and knowing really mean.

The word polymathy also really carries a lot of connotations that I'm not sure I've really thought about. The best way to really get started with building the foundations of the novel "knowing" theories to start from the most generic base possible that allows me to be as flexible as possible when it comes to understanding particular domains.

This isn't the first time I'm trying to redefine this pursuit : last time I went about it with the idea of building an identity: https://rajpatil.dev/post/aefraisk/. 

The try was sincere and it did help me quite a bit with approaching domains in a novel manner. I could still feel the shackles of sticking to a new character definition though. I'd just moved on from an societal connotation jail to intellectual house arrest.

Now that is an improvement but that still isn't true intellectual freedom. And in search of this true intellectual valhalla that I'm not sure about the existence of, I'll be departing for a long term journey not with an ideal character description in mind but a flexible attitude that allows me to really not shackle myself again to my own expectations.

I do feel I'll get to venture in unexplored intellectual galactic systems that have not been documented about before me due to any documented or undocumented reasons.

I'll also have to build up my own thought devices to customize my ways of thinking. I do not wish to create rigid systems but flexible organic templates that allow me to understand patterns that couldn't have been observed before due to existing idealogies restricted their expression in a certain manner.

I would begin with [[id:20240331T164431.280627][the Scientific Method]] as my seeding empiricism algorithm but won't be shy to break away from it (my irrationalism and rationalism approaches) from time to time or create a more personalized fork of the same to jump through epistemological and pragmatic hoops more effectively.

* Relevant Nodes
** [[id:7fa8612e-7547-4fc4-8e2d-c86da9fc488f][Synthesist]]
