:PROPERTIES:
:ID:       a4e712e1-a233-4173-91fa-4e145bd68769
:END:
#+title: Computer Networks
#+filetags: :cs:programming:

* Abstract
The notion of communication between Computers. Theoretically captured by the [[https://en.wikipedia.org/wiki/OSI_model][7-layered OSI (open systems Interconnection)]] model.

The OSI Layers:
 1. Hardware
 2. Data Link
 3. Network
 4. Transport
 5. Session
 6. Presentation 
 7. Application

The communication between any of the two layers across two computers is said to be compliant with the respective [[id:11d303f1-d337-4f51-b211-db435a9f2cd0][Protocol]].

Phsyical networking has its limitations in terms of the extent of simple abstractions you could employ. See [[id:714b029b-d0ac-4842-89f5-5f871d1a22c7][Software Defined Networking]] for alleviation of the same.

* Security
 - the complete domain of[[id:6e9b50dc-c5c0-454d-ad99-e6b6968b221a][ CyberSecurity]] arises out of this node and will be given treatises in itself.
 - one of the most pragmatic possible combinations of several technical domains out there, creatively.
* Practical
** [[id:24f4040a-7c18-416a-8460-e69280d437bf][Internet]]
** [[id:bc1cc0cf-5e6a-4fee-b9a5-16533730020a][Cloud Computing]]
** [[id:821aa28f-c16d-4982-bfc7-e1c9cf82c987][Service Meshes]]
* Tools 
** httping
 - https://www.vanheusden.com/httping/
** [[id:20b64349-a793-43f1-81bd-7abcdb5174f8][SSH]]
** ab
* Resources
 - https://www.computer-networking.info/
 - https://datatracker.ietf.org/doc/html/rfc1180 
 - https://github.com/saminiir/level-ip
 - https://www.youtube.com/watch?v=6G14NrjekLQ
   
