:PROPERTIES:
:ID:       e702ab85-cc45-480b-955b-0ef620690b52
:END:
#+title: Epistemological Cartography
#+filetags: :root:blend:

* Abstract
see [[id:aa78d0bb-76c6-414c-9660-445100742232][Epistemology]] and [[id:74cd7bc4-ea48-4c5e-a946-ea4125a6b618][Cartography]].
On the night of 0x2169, I found the idea of mapping abstract knowledge domains into a mental landscape to be quite attractive..

* Stream
** 0x2262
- thought of working with the arxiv dataset  https://www.kaggle.com/datasets/Cornell-University/arxiv
- would help create a good map of the scientific knowledge from the past 30 years.
- processing clusters would be more interesting than a single paper in terms of citation groups, etc.
- big information, or, in the spirit of this node, big epistemology or to be slightly nerdier, macro-epistemology does sound like an interesting domain to get into.
** 0x216A
 - Cartography usually refers mapping landscapes and terrains physically. I find the idea of mapping the abstract knowledge landscape.
 - might allow me to do some interesting things
   - abstractly map journeys between domains
   - define closeness and interrelatedness between domains
 - it might just have to be a math in itself
 - the physical world we experience is 4 dimensional (time + location): but I can explicitly see that I'll need to work in an indefinite number of abstract dimensions when working with an epistemological landscape.
 - I'll also have to develop notions of containing a domain within another
 - distance between two domains
 - how should I capture the indefiniteness between two domains?
 - need a more organic, flexible, non-rigid form of math that allows for possibilities: [[id:91b6fb5d-6447-43fe-8412-2054bb79979a][Probability]] might be a good starting point but there's a lot more that I need to reject than accept into the final model
 - once I correctly capture the notion of indefinite dimensions, I can start building up analogies of travelling between domains via different routes.
 - Symbolic Algebra could be a hyper-central node that allows you to reach any node fairly quickly.
