:PROPERTIES:
:ID:       9cac188e-8229-4c7a-9cb4-eeb5e81f8010
:END:
#+title: Reinforcement Learning
#+filetags: :ml:ai:

* Abstract

The machine (in the context of [[id:20230713T110006.406161][Machine Learning]]) lives in an environment and can interpret it's state in the form of a feature vector.

The machine can execute actions in these states and there are associated rewards with these actions which also alter the state.

The objective of a reinforcement learning algorithm is to learn a policy function, that, given the environment state, outputs an optimal (to maximize rewards) action to execute in that state.

The action is optimal if it maximizes the expected average reward.

[[id:20230713T110040.814546][Deep Learning]] can fit in here for mapping an environment state to an action that needs to be taken (see [[id:df953c8b-ecd1-4610-bc31-fa6a2e160fb6][Policy Networks]]).

* Interesting Caveats
** [[id:134fe7fe-cfd9-45da-8164-8f2c369bbeb3][Temporal credit assignment problem]]
 - if the rewards follow after an uncertain amount of time, causally tracking down the definite set of actions that led to that result is needed to formulate a policy
** [[id:8a8ef56a-8f0a-4bb0-a522-f7b081ace1c2][Exploration vs Exploitation]]
