:PROPERTIES:
:ID:       20240421T174402.732098
:END:
#+title: Authors
#+filetags: :author:meta:

* Abstract
Separating creators from their creations, understanding their distilled essence of a corpora of works over their lifetimes is an interesting exercise. I consider reading an author rather than segregating the works as they chose to present it.

With this node I intend to map out the transference, consolidation, rejection, evolution and creation of ideas across authors. This is an eternal work in progress and I wish to understand what the author really wants to convey rather than just what is presented in their works. I intend to read up on their works in the close future. This list is (of course) non exhaustive and will grow in scope as and when my interests expand.

One major intent to read influential authors is that several abstract and tangible phenomena are eponyms.

I'll be reading across cultures to extract generic patterns, with the overall intention being understanding the evolution of their thought more than criticising their works based on the current intellectual state of the art.

I'll be restricting myself to authors that talk more about eternal affairs than being limited to a specific era. Consequently, the list will be alphabetically ordered.

I'll be adding in here what I've read, the individual nodes contain all that I'd like to read (of course a long term affair).
