:PROPERTIES:
:ID:       9fae06f7-57f1-4f01-a811-543615e55bc6
:END:
#+title: Virtue
#+filetags: :psych:meta:

* Stream
** 0x21C4
Initialized the rhetoric node and thinking 
A starting point would be questioning the societally accepted [[id:9fae06f7-57f1-4f01-a811-543615e55bc6][virtues]].
One that I personally did so heavily early on in my life up until around 2 years ago was the virtue of patience.
 - unless you really don't question the worth of a quality, you're not actually virtuous enough when you choose to exercise that due to a prescription.
 - Most such virtues don't and probably shouldn't be inherent to us.

Honesty is something that again, is prescribed to us when we're kids and I haven't surveyed any toddlers but I think they're equally likely to display signs of deceit as much as they have a propensity for inate honesty.

Rather than questioning the superiority of one over the other, I'd rather prefer looking into the intrinsic incentives that are coupled with such exhibitions.

[[id:ab264138-da63-4e59-b124-db1833a66c9b][Incentives]] seem to play a universal role when trying to comprehend [[id:69d908d1-7a4d-46ea-8a01-cb02e67e9a2b][society as a whole]] as well as when it comes to individual psychology.

Variables such as if you're the individual or if you're a part of the crowd concerned play prominent roles in your perception of those particular incentives via your [[id:42564322-1093-4d29-9672-46cb4f056cc9][moral lens]].

For instance, I'm guessing you'd have very different moral reservations when it comes to severity of a punishment based on whether you're an independent observer or the victim of a crime.

I'm also guessing that defining such prominent subjects without absolute axioms and basing them on relative scenarios isn't a good seed for the healthy growth of a domain.

* Resources
 - https://plato.stanford.edu/entries/ethics-virtue/
