:PROPERTIES:
:ID:       6e9b50dc-c5c0-454d-ad99-e6b6968b221a
:ROAM_ALIASES: Hacking
:END:
#+title: Cyber Security
#+filetags: :programming:root:

* Abstract
Programs are just as secure as the intent and awareness of the programmer. Consequently, an important aspect of exploring CyberSecurity as a domain is rooted in [[id:20240218T063419.065184][Social Engineering.]] 

I've Aliased this node as Hacking as well but I do acknowledge the more respectful "elegant programs" sense of the word "[[id:20240218T065014.753109][hack]]" as it was originally intended to be used.

Wish to keep nodes relatively colloquial rather than being correct to a fault when it comes to common interpretation of these notes.

I'll refrain from using "hacking" anymore in these nodes unless I really mean hacking away at something with an axe.

As for thinking in an offensive manner, as many have already documented, understanding a system's weaknesses is the most explicit way towards strengthening its defenses.

* Relevant Nodes
** [[id:68184953-e9ff-456d-acc9-533b522d9743][Cyber-Forensics]]
* Resources
** Hacking: the Art of Exploitation
:PROPERTIES:
:ID:       14f6375c-110b-46be-b7d1-3a5b14cdb8d2
:END:
 - following the book to learn about what computers really are and to be able to think about secure software
 - not explicitly relevant to my domain but I'm generically into computers and wish to know more
 - will not be posting notes as they are from the textbook, but will be populating nodes without too many explicit linkages.

** Linux basics for Hackers
:PROPERTIES:
:ID:       310eb440-587c-4927-9b06-e2f3e0efb647
:END:
 - occupy the web
 - actively building cybersec skill
** OSSF best practices
- https://best.openssf.org/
