:PROPERTIES:
:ID:       21008bf7-42c5-496b-a7a4-43e8df15e242
:END:
#+title: Poetry
#+filetags: :meta:

I published my first poem (one about being aware enough to know that one's not aware enough) on my website here : https://rajpatil.dev/i-know-not/

Thinking of exploring a unique genre of distilled abstract literature again given my epistemological appetite is on the rise again. Reading more poetry will be the first step in understanding what actually the brain finds so intricate about such dense literary excerpts that make them so memorable.

This should be an index of me analysing some poems that I find interesting and some of my own.

I don't particularly have ambitious expectations other than to be able to "intellectually" penetrate minds and hand out intellectual orgasms on demand: that is definitely quite the superpower.

Soon, I should be able to carve out my own genre post understanding the tools of the trade and this should also infuse a sense of elegance in the way I normally speak: I mean.., I'm not complaining...


* Cyclical Adages (Explorations in [[id:e94b1ff3-ee62-417f-8d01-afb23ccd0c3b][Linguistic]] Transitivity)

 - I do have a tendecy to craft some of my own adages when I'm in specific situations of my life.
 - combine that with existing ones and I have a somewhat esoterically satisfying idea that could be a good segue into a genre of itself.
 - Behold -> transitive adages.
 - The goal of an entry is to connect one adage to the next via a common entity.
 - The incentives of the adages are independent and don't have to be correlated.
   - more points though, if one can build interesting transitions
 - Let's see if I can build a large cycle (no bidirectional edges)
   
** (incomplete) Butterflies -> ...
*** Butterflies and Garderners

 #+begin_quote
Why chase gardens as a butterfly, when you can enjoy the view of several being a gardener?
 #+end_quote

 - I crafted that from some source I might have encountered somewhere I don't completely recall

*** Garderners and Warriors

#+begin_quote
It's better to be a warrior in a garden than a gardner at war
#+end_quote

 - this is an old japanese saying if I recall correctly

*** War and Love

#+begin_quote
Everything is fair, in war and love
#+end_quote

 - I understand this is mainstream, but it does get the ball rolling
   
*** Love and Loss

#+begin_quote
Better to have loved and lost, than to never have loved at all
#+end_quote

 - As I am right now, I do agree with that

*** Unlost wanderers

#+begin_quote
Not all those who wander, are lost
#+end_quote

 - Tolkein : Fellowship of the Ring
 - I read the poem already anticipating the impending satisfaction I experience once a cycle completes
   
