:PROPERTIES:
:ID:       88f03140-7c60-41aa-b191-63e1460e76bd
:END:
#+title: ffmpeg
#+filetags: :cli:tool:

* Abstract
** FFmpeg Overview
FFmpeg is a free, open-source command-line toolkit for multimedia processing. It functions as a comprehensive solution for handling audio and video files.


#+begin_src plantuml :file images/ffmpeg-overview.png :exports both
@startuml
'skinparam linetype ortho
skinparam rectangle {
    StereotypeFontSize 10
    StereotypeFontName monospace
}

rectangle "Input\n(Demuxing)" <<file format>> as input
rectangle "Decoding" as decode
rectangle "Transformations (Optional)" as transform
rectangle "Encoding" as encode
rectangle "Output\n(Muxing)" <<file format>> as output

input -down-> decode
decode -down-> transform #line.dashed
transform -down-> encode #line.dashed
encode -down-> output

@enduml
#+end_src

** Core Features:
- Decoding and Encoding: Supports a wide range of multimedia formats (video, audio, subtitles) for both reading and writing.

- Transcoding: Converts between various codecs (e.g., H.264, H.265) to optimize compatibility and compression.

- Manipulation:  Enables cutting, trimming, concatenating, splitting, and rearranging audio and video streams.

- Processing: Offers filters for color correction, noise reduction, resizing, and other effects.

- Streaming: Facilitates sending and receiving live multimedia streams over networks.

- Analysis: Extracts metadata and other information from multimedia files.

** GUIs
- [[id:02abc3f4-0caf-481d-a439-80bf86f1740a][HandBrake]]
- Lossless Cut
* Resources
 - https://ffmpeg.org/ffmpeg.html
