:PROPERTIES:
:ID:       21008bf7-42c5-496b-a7a4-43e8df15e242
:END:
#+title: Poetry
#+filetags: :meta:

I published my first poem (one about being aware enough to know that one's not aware enough) on my website here : https://rajpatil.dev/i-know-not/

Thinking of exploring a unique genre of distilled abstract literature again given my epistemological appetite is on the rise again. Reading more poetry will be the first step in understanding what actually the brain finds so intricate about such dense literary excerpts that make them so memorable.

This should be an index of me analysing some poems that I find interesting and some of my own.

I don't particularly have ambitious expectations other than to be able to "intellectually" penetrate minds and hand out intellectual orgasms on demand: that is definitely quite the superpower.

Soon, I should be able to carve out my own genre post understanding the tools of the trade and this should also infuse a sense of elegance in the way I normally speak: I mean.., I'm not complaining...
