:PROPERTIES:
:ID:       b5576a88-d12a-4779-958b-03ad4f4c6403
:END:
#+title: Business
#+filetags: :bs:

* Abstract
** Personal
This node set is about the pragmatics of business, adapted to my (ever-evolving) incentives.

I have some formal education in Business (took Business Studies during GCSE for two years (age 14-16)) and I was always inclined towards creating value in a sustainable manner, with personal temporal freedom also being a major motivator.

Having recently begun working on [[id:95dd2f7c-e699-4ff6-9f40-52d573527107][theBitMage]], I want to fill in the gaps that the lack of practice has introduced in my approaches, over time.

This node-set is going to be a deep practical analysis of the aspects of business applied to my needs.

I am, as of 0x229F, in the dark when it comes to the ground realities of a operating a business. [[id:ab7c582a-9b00-4e4d-a71c-302efdc1f0e7][The iterative Read-Act-Write (RAW) protocol]] is being applied to this one. The contents encompassed can therefore be considered reliable.

Parallely initializing a fundamental read, I'll be conducting experiments on the aspects of this node set.

** The Etymology
#+begin_quote
Business originates from the Old English "bisignes", meaning "care, anxiety, occupation",  highlighting its association with effort and activity.  Over time, it evolved to encompass trade and commerce, emphasizing the transactional nature of engaging in an endeavor for profit.
#+end_quote
** A Succesful Business can:
 1. [[id:5b8b5a9d-0c0a-4e26-8716-6399e979bd1e][supply]] something of [[id:c9942084-31af-424e-bc2b-41800004fa24][value]]
 2. that the [[id:f271220c-7cdc-449e-b5e6-90b6583b0fae][market]] [[id:3ddd1a63-e5cc-4039-a170-42af81674a6f][demand]]s
 3. at a mutually agreed upon [[id:98f9c55c-c14a-4ff3-b5f2-79318d7be1f3][price]] that
 4. satisfies the demand
 5. while generating enough [[id:c42d5bac-d922-45ef-ae68-0758609e5592][revenue]] to make it worthwile for continuing [[id:026cebc6-e388-4e7e-84ce-b46d8f3151a9][operations]]
* Misc
** [[id:20230815T212630.336328][questions]], not Answers
 - framing the current situation well with the right questions is much more important than knowing the right answers to a specific problem.
 - learning to ask better questions then should be the objective, not accumulating answers to constrained scenarios.
** Leverage [[id:20240218T061653.528745][Abstractions]]
 - understanding everything with complete depth and breadth is not my objective.
 - learning to regularly upgrade your [[id:20240114T210722.836738][Axiom]]s to a relevant level allows you to bypass fretting over the unnecessary details and better direct your efforts towards the current [[id:187d2839-8a3b-479c-a745-c1195965ed43][bottle necks]].
 - for instance, as of now, my bottleneck would be the uncertainty in my awareness about the fundamental aspects of a business: consequently, as of 0x229F, the most profitable action for me is educating myself on the matter.

* Skills
** [[id:5b5601de-511f-4034-9af9-e3e17f5ae622][Sales]]
** [[id:5c3d1afc-5ba6-4cce-b0c3-3594c28813f7][Marketing]]
** [[id:bb517f51-4272-4543-9d1e-f79b22f16a4d][Finance]]
** [[id:026cebc6-e388-4e7e-84ce-b46d8f3151a9][Operations]]
** [[id:9c63b373-804e-48b0-bc95-032481c70fa3][Product Development]]
** [[id:c042e4d1-3575-4f8d-840c-3898148c0e12][Customer Service]]
** [[id:ee45dace-4ea9-4415-abd6-74bd2930df37][Human Resources]]
** [[id:20240218T064356.582939][Psychology]]
** [[id:11847f5f-5337-425b-bacb-575f77690a4b][Systems]]
** [[id:8d7067b7-084f-4c25-a8e0-609bbbe6fac6][Networking]]
* Overarching Aspects
** [[id:2da7b9ea-7bf0-4e7c-8e55-2a4113fa1584][Value Creation]]
* Resources
** Book : The Personal MBA
:PROPERTIES:
:ID:       d9166a1b-cca7-4167-939c-2a2256485e5d
:END:
