:PROPERTIES:
:ID:       1d3f785e-9c83-4df7-a308-313ef5ca3598
:END:
#+title: Achievements
#+filetags: :meta:

I have a somewhat indifferent approach towards achievements(mine and others'): with a tendency to gauge the other personality based on how our conversations flow and in terms of the quality of questions we interchange.

Recently, I've began to grasp why they might be a necessary construct:
 - when leading larger societal initiatives, simply being ethical and claiming morally superiority doesn't pan out well (and it shouldn't) with gaining trust of the masses
 - you need displays of competence for people to will their incentives to align with yours somehow (for collective progress)
 - claiming dignity is simply not enough.
 - of course, this opens up a whole bunch of societal games and dynamics that are too complicated for me to completely break down right now.



If you do wish to make a change, you will someday have to take the helm of larger groups of humans. This is when being competent and having proofs for it becomes indispensible.

Although I find it a little saddening to chase tags and accolades explicitly, I do enjoy the idea of improving towards being the best, irrespective of the tangible recognitions.

This is again related to one of my other introspections that I rarely discuss:-
 - if the actually competent start practicing ignorance towards the larger responsibilities in society..
 - the leadership positions would actually start to be occupied by personnel that optimize for attaining that leadership and not ones who are actually the most competent for carrying our the responsibilities pertaining to it.
 - finally, these occupancies affect every ones' existence and ignoring power just for the sake of being "beyond such earthly notions" is then a more selfish act than chasing these titles, for the service to society is sub-optimal than it could have been.
