:PROPERTIES:
:ID:       1729
:END:
#+title: Index

Hi, this is Raj. You've chanced upon my digital note-box (~Zettelkasten) maintained in org-roam. I've circled over a lot of tools to maintain an efficient over the past and have finally settled on a format that treats everything as text and allows me to spend more time with emacs. I find it difficult to keep track of all that I learn and this buffer intends to delegate the notion of remembering to a computer.

I like building connections between domains that are seemingly distinct: I'll be keeping it simple and this note-box will act as an intermediary for the all the [[id:20230712T131112.909632][blogs]] that I intend to regularly push out henceforth. I believe it should be simpler for me to improve my writing skills if I have an informal setup - other than my [[eww:rajpatil.dev][main blog]] - where I experiment with varying styles and not worry about compatibility issues with my existing work.

A major proportion of the nodes in this web will be in a transient phase at all times - completeness is not a goal for each session : this is the input buffer. More polished versions will be posted on the main blog once a node(set) matures and is worth sharing.

I will be [[id:20230712T132110.496747][timestamping]] the notes so as to be able to keep track of how a node(set) evolves.
