:PROPERTIES:
:ID:       1729
:END:
#+title: Index

* Global Disclaimer

What I compile in these notes isn't meant to be a factual state of the art but how I currently perceive whatever I've partially captured in them.

Expect [[id:be99b67e-e454-4f19-ade7-4c3faf10ce07][paradoxes]], inaccuracies, [[id:d3617afa-85ce-4ac8-bdc3-19fe587c1956][pseudoscience]] and some occasional epiphanies. It's mostly rambling but that is necessary for the rare insight that brings calm to the chaotic combination of concepts that are a prerequisite for a fertile [[id:fef55c48-87a6-4828-a298-4326264fc0e5][Mind]].

I also consider deliberately intellectually [[id:f3347380-f482-4077-a89b-a3ff059b4af6][hallucinating]] so that I can churn up [[id:5a68c46a-85bf-49f1-a589-5a6116f839fb][reality]] a little to chance upon the silver linings that help one push abstract boundaries.

* Endpoints
** [[id:1729][Index]]
 - notes down some basic rules about the braindump's usage
 - stream of generic comments pertaining to the overall logs
** [[id:20230815T212630.336328][questions]]
** [[id:7382d50f-a0aa-4370-baa9-83bb39ccbe1a][resonant-with]]
 - an collection of ideas that I'm resonant with and would like to cache to remind myself of again, sometime down the lane.
** [[id:20230718T222456.978981][input-queue]]
 - an index of resources that I want to consume sometime down the lane
 - anytime I feel like I wish to learn something, I visit this node and populated the buffer accordingly as I learn new skills and accumulate info
** [[id:296b118e-ff24-4423-b343-eb5160102095][work-setup]]
 - a stream of updates pertaining to my physical and cyber work environment
   - might even include updates for mindset changes tending to how I approach work.
** [[id:20231112T080937.669416][Projects]]
 - a cache for ideas that may never see the light of day again.
   - or they just might...
** [[id:cc418612-7343-4251-a146-042e0cc2b5e1][Prune]]
** [[id:3dc89742-51ee-49dc-bb3b-19bd24e50c8a][problems]]
** [[id:65f7fdfb-e6b4-4135-bce5-be9efe390549][AWESOME]]
 - any time you see this header for a node, you may treat it as a generic index into things pertaining to that particular domain.
 - think awesome : https://github.com/emijrp/awesome-awesome
** [[id:5bf59607-5845-417a-8093-7fd971e7ab21][Intriguing Works]]
* Domain Specific Indices
** [[id:53f365ac-8ee6-48d9-8847-f56ef3681891][System Design Index]]
** [[id:1c70d2a6-8296-41aa-9148-08f52f62a5cb][AlgoIndex]]
** [[id:7d86f493-37aa-4ea9-bc1f-2db159b1f02d][DSIndex]]
* Domain Specific Glossaries
** [[id:3aa7ff5b-e9d4-4f19-ba71-bb5e94880708][CS Glossary]]
* Stream
** 0x22F1
 - the idea building up an eternal internal discussion that deeply thinks anything around you seems interesting
** 0x22F1
 - thinking of explicitly trying to identify value creation opportunities
 - I am a consumer of value so far but not a creator in the sense that general society would find it useful.
 - opportunities, of course, do exist everywhere but I just need to hone in on being able to observe and capitalize on them
 - might involve an explicit shift needed to move from the mindset of learning new abstractions to identifying problems around me.
 - I feel I'm also technologically deprived of hardcore problems.
 - will returning to some low level stuff for the fun of it.
 - I'm really bored and getting started with writing an operating system.
 - in fact could start reading up on physics again, for the sake of itself..
 - sort of intellectually angry in some way.
 - aggressively ramping up my reads as well: I'm asking for an overload : life's boring at the usual intellectual pace that I've been maintaining for quite some time now.
 - wish to explore the harder aspects of computer engineering: distributed computing is sometime down the chopping block
 - might also start blogging like a purely technical guy that doesn't care about his audience.
 - this needs to be done.
** 0x22EA
 - my mechanisms are pretty smooth around the edges now
** 0x22E7
 - allocating every friday half to clear up all the ancillary tech that I get into..
 - I tend to push a lot of smaller interesting technologies and things into my INQ and NA
 - having a dedicated flush from them every weekend sounds systematic
** 0x22B8
 - going a break from youtube : will return on <2025-03-01 Sat>
 - I forget to have some deliberate from time to time
 - actively scheduling in enjoyment and relaxation is essential to your incentives not dampening down in the long run
 - I find myself to be lucky to find joy in learning and writing about random things out there
 - today I had the thought of pursuing higher education in physics later down the lane so that I can earn the noble title of a physicist (I already look like one now).
 - I tend to lose sight of the present from time to time for the sake of the immediate future.
 - that is not something that I'm proud or ashamed of but have been noticing that isn't exactly a good strategy to maximise one's long term mental gains from the activities that they partake in.
 - I was bed-ridden for a while (diagnosed with dengue around 3 weeks ago, recovered 2 weeks ago) and had to let go of my routines for a while.
 - I have picked up a few things with greater intensity but am yet to incorporate all that I was doing before completely.
 - what I learned though, was to be okay with resting for a while here and there and not worrying about progress.
 - now, I'm a productivity nut, and I'm not going to say there's more to life (there is but that is a very poor excuse to not indulge in this game with the best of your abilities), but it's worth slowing down from time to time to better refine your ambition compass, instead of the enduring mental drain that ensues if not dealt with, with awareness.
** 0x22B8
 - found out roadmap.sh
 - might consider shifting most of my studying workloads to it.
 - picking up "The HitchHiker's Guide to the Galaxy" for the 5th time : I've put it down 20 mins into it, all the times, so far.
** 0x226C
- setup biblio + citar in doom
- exploring neurosymbolic AI -
  - [[id:5ec6cae2-7c8c-467b-b5a6-6bb9edd1bffd][Sheth, Amit and Roy, Kaushik and Gaur, Manas :: Neurosymbolic AI – Why, What, and How]]
- working with citations:
  - export references.bib via Zotero to be used by citar.
  - create relevant notes with citar-open-notes
  - this creates a roam node that can then be referenced normally
  - emacs isn't to be used to manipulate the references file
  - always only export from zotero
** 0x2267
 - setup an AI usage disclaimer
** 0x2262
- will be booting some frustrating habits over time that I've acquired unknowingly.
- these should be generic patterns that don't pertain to anything specific but span several domains.
- they are generic habits, the effects of which trickle down into all aspects of my life.
- keeping these nodes free from any personal burdens : this has incentivized me to maintain a commonplace notepad.
** 0x2250
 - studying more, blogging more
** 0x224D
 - haven't recorded a day dream in a while
 - starting out with random thoughts in here again
 - I turned 24 recently but totally don't feel like it.
 - 20s are definitely confusing. 
 - bought a foam roller and a massage gun 2 weeks ago.
   - good: recovery delays have lowered and sleeping better
 - 1 based indexing sounds crazy:
   - this is the reason I'll actively try out lua
   - I say actively cause passively do use it for configuring neovim
 - was thinking of writing on how I study given the current scenario of knowledge and artificially intelligent tools conveniently at our disposal
 - need to think what really matters more 
 - actively going to think of problems worth solving
 - also looking to attend some technical conferences soon
   - by looking I mean listing out what and where I'd like to go
   - missed out on the european lisp symposium (vienna) this year
   - bummer..
** 0x2233
 - Actively decoupling any monetary incentives when it comes to writing for a while
 - This is going to be a meta profession with the intention of creating valuable works
 - I do not shun monetizing such an activity but I need to get good and be worthy of the value I claim to create before I worry about the returns.
 - actively focusing on building value rather than fetching returns for a while.
 - ready for a long span of writing for the sake of itself, building a repository of worthy insights.
** 0x2230
 - I took a 5 day break from caffeine to get my sleep in (fending off a cold) and maintain good hydration levels.
 - had my first cup today morning : it's almost as if I'm reborn
 - will be writing more soon.
 - maybe a cold is just the natural signal I needed to reset my caffeine tolerance twice a year.
** 0x2223
 - will soon dive deeply into the notion of negative rewards
   - not from the perspective of reinforcement learning but from that of psychology
 - I feel like I could dissect what makes a good poem in general
 - should help with my prose and my push towards being a more elegant essayist
** 0x221F
 - settled down into a stable and productive circadian cycle.
 - exploiting the good kind of boredom for peak productivity
 - learning to relax a little to tackle burnouts
** 0x2211
 - starting out a block of hyperlearning
 - emphasis on precision and the exact differences between the concepts under discussion
 - pausing the creativity for the while
 - will be focusing completely on understanding first initially : there's quite a lot that I am not yet completely aware about the workings of
 - trivial knowledge is pre-cursor to pushing boundaries with ingenuity
 - lofi classical is going to be the go to auditory nootropic strat this cycle
 - have tried techno previously and expect this to help me loose myself somewhat quicker and a more stable manner
** 0x21F1
 - beginning to dive deeper to build repositories that represent true insight and don't just mimic a micro-wikipedia.
 - will be focusing on condensing abstractions into descriptions that are just enough : terseness is key
 - I'll be having more streams on generic nodes (has to be tagged as root) to allow capturing an evolution in thought rather than just a static overview of the domain
** 0x21EA
 - intialized the first ever fictional node: my head is full of references from great works that I wish to document for my descendants and the rest of humanity
 - experiencing an increased intellectual appetite lately and experiencing a new kind of insatiable hunger that I don't see myself being able to quench any time soon. 
 - don't know the point that will be enough : that inspires and excites me for the future
** 0x21E8
 - diving into boredom seems to be the best way to tackle it.
 - explicitly running head on into the act of being bored probably allows you to truly understand its superficial nature.
 - I have a tendency to get bored a little too easily. But I also believe I've got this weird tendency to enjoy phases of boredom by filling them with interesting activities.
 - In my pursuit for varied skill acquisition (the wannabe polymath syndrone), I can enjoy reading anything that is accessible to me
 - Writing flow does seem to be an interesting hobby as well and that does allow one to build up a portfolio of tackling boredom in case you do it regularly and right.
 - I'm already carrying a pocket notebook so my writing and comtemplativeness has already spiked in the past few days. To keep it up, the key is to be able to write anywhere you go: top of a mountain, post lunch walk in a garden, anywhere.
 - You should also somewhat be able to write anything without any sense of curation i.e. feel free to spill out rubbish
 - Music seems to be tricky to figure out for work sessions : I've got these zeroth world problems that very few humans bother to wonder about.
 - Have been reading this book by tony fadell for some time (Build) and really wish to be building something useful. 
   - Bet everyone has that feeling from time to time : to be "of Use" - but the act of being creatively useful probably is never preceded by such a thought and could even be a selfish act in some scenarios.
 - Have been learning Go to build some services and feelings boring as heck - compared to my dreams in lisp, dreaming in go would just be like ..., normal...
   - anyway, collaboration is important to build larger products and I'm willing to sacrifice moments of boredom to get an output.
 - feel like I've got to start pruning outlets of my efforts into limited ones.
** 0x21E7
 - Am getting into another cycle of learning heavily and documenting the same in the nodes here.
 - have been grateful recently to receive opportunities that allow me to study and connect several domains.
 - as of now, completing a practical openCV overview.
 - Soon, will be diving into advanced cloud compute and the practicals thereof.
 - will also be replacing all minor passtimes with writing whenever I feel like I'm out of focus. This should be a very good exercise in understanding the true nature of my work capacity and what my brain do.
 - feel like I'm entering a phase of my life, when I'm expecting slow, stable progress when it comes to my skills and ability get things done i.e. building a true work ethic that I myself can respect and don't look down upon.
 - this does involve a whole bunch of writing about what I learn, hiking, lifting weights, putting in the hours, practicing patience and just learning to build good stuff. 
** 0x21E0
 - have started using neovim for my programming endeavours
 - still write in gcc emacs and now have a distinct mindset for when I write and when I program
 - I feel that's better than trying to fit everything into one tool.
 - my full-time in emacs wasn't a waste and I've picked up on several useful habits.
 - neovim just seems to be better at cutting through the fluff and is more tailored towards environments I usually work in (remote shells).
** 0x21B1
 - when discussing domains and talking about their overlap, I can qualitatitively judge the closeness of two domains by a metric I picked from my days when I worked in the domain of semantic Segmentation.
 - enter : [[id:e6c6918c-25bd-47f4-830a-4221452885e8][Intersection Over Union]]
 - I'm feeling pretty confident about introducing abstract, partially ordered relations between domains:
   - is a step towards building the [[id:825d36cc-4e03-48e5-bca8-0845e51090af][The Meta-Subject]] 
** 0x21A3
 - getting into the idea of intellectually rambling on the internet
 - I explore something of immediate intrigue and try to update the current state of the dump according to what I consume.
 - a few blurry rules that'll help me not [[id:f3347380-f482-4077-a89b-a3ff059b4af6][hallucinate]] more than I can handle:
   - no resource links to be inserted during such sessions -> wikipedia is a cheatcode only to be used for factual notes
   - all that is inserted needs to be typed in
   - be precise: prune freely, add carefully.
   - verbosity is to be reserved for streams such as this
   - no work related stuff : explore something from a completely different domain
   - a question can serve as a seed for the session but refrain from using the internet right away. Only do so to refine your thought.
 - for today's session, I'm considering talking about meditation: have been regular for 2 weeks for atleast 20 mins a day - somedays are 40 mins long.
   - and I have some interesting thoughts about the "mind" and the nature of the "I".
   - minimizing prior assumptions that aren't well rooted in experiences, off I go ...
** 0x219D
 - careless parenting:
   - henceforth, In these nodes, I'll refrain from making the parent refer the child nodes.
   - the child will be pointing back to the root node instead.
   - that isn't ideal for textual navigation but is sufficient and when using a Graph like Org-roam-ui to visualize the nodes
   - this calls for some pruning : will need to schedule quite a session to actually enforce these regulations so that the network isn't unnecessarily crowded with two way links.
 - Now that I've shifted to neovim for work, only all of my writing and note-taking happens in emacs (+ lisp) so I guess I'm slowly learning to set healthy boundaries in my relationships now.
 - I changed my mind:
   - only the parent logs abstract comments about the child and the child doesn't refer the parent explicitly with "rooted at ..." unnecessary appendices
   - will need to prune the sh*t (I don't know why I'm censoring) out of this someday now.
   - careless children are the way to go.
** 0x2196
 - will be actively populating and pruning the zettelkasten a little more often henceforth.
 - really dialling down into the writer's persona : let's find out what's on my mind and is any of it really worth anything...
 - It will be a mix of writing and research and throwing pointed questions toward the internet to build a more intricate knowledge network over time.
   - I'm hoping this will help me generate a lot of ideas for writing : for AI, lisp and epistemology in general
   - I find a formal reading of a textbook to be a completely different than what I'm going to do for a while.
 - LFG....
** 0x2195
 - contrary to conventional advice, I'm trying to read less than I usually do. On the contrary, I'll be writing more often and be spending more time with my own abstract concoctions. I have noticed that when I'm on a lean intellectual intake or even abstractually(this isn't a word) fasting, I'm creating a lot more and much more original stuff that isn't your run of the mill wanna be writer. Irrespective of the meta-qualitative-aspects of the excerpts and videos I pump out, the sense of satisfaction that I experience when I publish is much more important than the robotic feeling when I produce conventional chunks.
 - I will however be continuing to read works that call for an action and will help me in my immediate pursuits - be that fitness or technical domain expertise.
** 0x2173
 - so, I'm finally done pruning some nodes that weren't serving any purpose.
 - I've also stabilized in my org-mode GTD workflow and find checking tasks off to a be oddly rewarding.
 - It's much better than doing what's more important at the moment.
 - Also working on creating deadlines for me and sticking to them.
 - planning for relaxation is something that I've started doing recently and not caring about work for a definite chunk of the day is worth it.
 - I do seem to have accumulated some writing inertia and considering my brain dump, the main blog and actual work, I've been experiencing fatigued fingers at the end of my workday, almost daily.
 - Also getting back to elevating my typing speed after 5 years.
 - I practiced then and reached upto 100 wpm without punctuations, capitals and numbers.
 - I've sustained it and typing is never a bottleneck
 - Now, I'm adding punctuations, capitals and numbers to my practice sessions (15 mins daily) and am targeting around 150 wpm
   - that is around 12.5 cps (characters per second) - shifting the unit cause this has a nice ring to it.
   - as expected, my speed with all the additions now is around 5 cps
   - deliberately working with harder lessons (unexpected combinations as well) : akin to living with ankle, wrist and torso loads.
 - I think I might start meditating again.
   - I go through cycles of enchantment and boredom in terms of my views for the same but I've noticed it does really help with focus.
   - I usually fit in a 10 min session post workout, pre breakfast and find that my day is more structured and I'm able to get more done on these days.
** 0x2172
 - finally getting around to organizing stuff a little and laying some ground rules
** 0x216A
 - will be cleaning up nodes soon, probably today evening
 - do need a proper place to index the status of some major trees
   - mostly divided in sections like WIP, matured and so on..
 - experiencing stable levels of focus in sessions and the L-tyrosine and good sleep cycles seem to be doing their job well.
 - did chalk out several ideas yesterday on a techno post shower night walk
   - a lot of them are actionable and can be used in the kind of content I'd like to create
** 0x215F
 - need to have a pruning session sometime - a lot of unnecessary nodes that could be better restructured as sub-trees.
 - some nodes are just plain useless and are an itch I scratched gone itchier.
** 0x2154
 - an explicit :wip: tag denotes that I'm actively working on that node (different from :transient:)
** 0x2138
 - the [[id:20230812T200515.697950][literate programming]] setup is live and working well with the publishing script.
 - I have it setup for rust, common lisp and elisp for now
 - mermaid-cli also works for flowcharts locally but need to figure out the publishing process for it to be rendered properly on the online buffer -> UPDATE (2 mins after I pushed this) : just needed to put in an ~exports: both~ in the src blocks..
 - making notes is second nature to me now -> whenever I'm studying/want to start a new project, I don't have to think much in terms of how I'll document the process. The snowball is rolling.
 - Noticing an significant decrease in the pre-thought of remembering stuff before I get start with a domain. Now that it is delegated to something with the memory of a steel trap, all that I learn is a few keystrokes away.
   - surprisingly, I have a mental parallel of this web that I implicitly call upon when remebering stuff -> that is an unexpected and beautiful side-effect...
 - Errors may creep in aynwehr -> I do'nt particurlayl edti what I wirte here and  all is typed in a single pass, along with my thoughts.
   - this might result in needlessly long structures that could be better organized. Of course, I don't do this for the main blog. The buffer is not something that I maintain for perfectionism, but for maintaining a playful approach towards my studies.
** 0x2118
Here are some conventions that I follow to organize my work:
 - [[id:20230712T132110.496747][Timestamps]]
 - will be expressing math as [[id:20230712T223044.319985][S-expressions]] rather than latex
   - the former flow fluidly off my fingers
   - the latter I'll reserve when for publishing on the main blog: latex isn't exactly good while note taking - is a distraction.
   - my goal being encoding the concept (procedure/definition/relation) in a way that is more accessible to that of a programmer's mind
   - I also choose to do so as it'll help me learn map concepts from different domains into a common symbolic representation (hmmmm ... : yeah...., math already does that - I guess I'm just being peevish)
 - A top-down knowledge building style : the human mind doesn't remember what it knows. Trying to remember a specific latent knowledge node in this graph will be more efficient than building all the base nodes one by one until I reach a practical level of application. I will add atoms as and when I see fit : I might even insert most from memory.
 - each major node has its own idea buffer to keep note of specific ideas that I haven't organized yet.
 - at any given point of time, several emtpy nodes may exist : I'm not trying to be exhaustive right away when exploring a domain. This is supposed to be an eternal work in progress. However, to indicate that I intend to work on a node later on and it's not just an empty atom, I've placed ~:tbp:~ (to be populated) tags on such nodes.
