:PROPERTIES:
:ID:       1729
:END:
#+title: Index

* Endpoints
** [[id:1729][Index]]
 - notes down some basic rules about the braindump's usage
 - stream of generic comments pertaining to the overall logs
** [[id:20230718T222456.978981][input-queue]]
 - an index of resources that I want to consume sometime down the lane
 - anytime I feel like I wish to learn something, I visit this node and populated the buffer accordingly as I learn new skills and accumulate info
** [[id:20230712T131112.909632][blog]]
 - log of all blogs that  I write down and relevant notes for future works
** [[id:20230727T192932.286062][Youtube]]
 - log of all videos along with plans and indices into drafts
* Stream
** 0x2173
 - so, I'm finally done pruning some nodes that weren't serving any purpose.
 - I've also stabilized in my org-mode GTD workflow and find checking tasks off to a be oddly rewarding.
 - It's much better than doing what's more important at the moment.
 - Also working on creating deadlines for me and sticking to them.
 - planning for relaxation is something that I've started doing recently and not caring about work for a definite chunk of the day is worth it.
 - I do seem to have accumulated some writing inertia and considering my brain dump, the main blog and actual work, I've been experiencing fatigued fingers at the end of my workday, almost daily.
 - Also getting back to elevating my typing speed after 5 years.
 - I practiced then and reached upto 100 wpm without punctuations, capitals and numbers.
 - I've sustained it and typing is never a bottleneck
 - Now, I'm adding punctuations, capitals and numbers to my practice sessions (15 mins daily) and am targeting around 150 wpm
   - that is around 12.5 cps (characters per second) - shifting the unit cause this has a nice ring to it.
   - as expected, my speed with all the additions now is around 5 cps
   - deliberately working with harder lessons (unexpected combinations as well) : akin to living with ankle, wrist and torso loads.
 - I think I might start meditating again.
   - I go through cycles of enchantment and boredom in terms of my views for the same but I've noticed it does really help with focus.
   - I usually fit in a 10 min session post workout, pre breakfast and find that my day is more structured and I'm able to get more done on these days.
** 0x2172
 - finally getting around to organizing stuff a little and laying some ground rules
** 0x216A
 - will be cleaning up nodes soon, probably today evening
 - do need a proper place to index the status of some major trees
   - mostly divided in sections like WIP, matured and so on..
 - experiencing stable levels of focus in sessions and the L-tyrosine and good sleep cycles seem to be doing their job well.
 - did chalk out several ideas yesterday on a techno post shower night walk
   - a lot of them are actionable and can be used in the kind of content I'd like to create
** 0x215F
 - need to have a pruning session sometime - a lot of unnecessary nodes that could be better restructured as sub-trees.
 - some nodes are just plain useless and are an itch I scratched gone itchier.
** 0x2154
 - an explicit :wip: tag denotes that I'm actively working on that node (different from :transient:)
** 0x2138
 - the [[id:20230812T200515.697950][literate programming]] setup is live and working well with the publishing script.
 - I have it setup for rust, common lisp and elisp for now
 - mermaid-cli also works for flowcharts locally but need to figure out the publishing process for it to be rendered properly on the online buffer -> UPDATE (2 mins after I pushed this) : just needed to put in an ~exports: both~ in the src blocks..
 - making notes is second nature to me now -> whenever I'm studying/want to start a new project, I don't have to think much in terms of how I'll document the process. The snowball is rolling.
 - Noticing an significant decrease in the pre-thought of remembering stuff before I get start with a domain. Now that it is delegated to something with the memory of a steel trap, all that I learn is a few keystrokes away.
   - surprisingly, I have a mental parallel of this web that I implicitly call upon when remebering stuff -> that is an unexpected and beautiful side-effect...
 - Errors may creep in aynwehr -> I do'nt particurlayl edti what I wirte here and  all is typed in a single pass, along with my thoughts.
   - this might result in needlessly long structures that could be better organized. Of course, I don't do this for the main blog. The buffer is not something that I maintain for perfectionism, but for maintaining a playful approach towards my studies.
** 0x2118
Here are some conventions that I follow to organize my work:
 - [[id:20230712T132110.496747][Timestamps]]
 - will be expressing math as [[id:20230712T223044.319985][S-expressions]] rather than latex
   - the former flow fluidly off my fingers
   - the latter I'll reserve when for publishing on the main blog: latex isn't exactly good while note taking - is a distraction.
   - my goal being encoding the concept (procedure/definition/relation) in a way that is more accessible to that of a programmer's mind
   - I also choose to do so as it'll help me learn map concepts from different domains into a common symbolic representation (hmmmm ... : yeah...., math already does that - I guess I'm just being peevish)
 - A top-down knowledge building style : the human mind doesn't remember what it knows. Trying to remember a specific latent knowledge node in this graph will be more efficient than building all the base nodes one by one until I reach a practical level of application. I will add atoms as and when I see fit : I might even insert most from memory.
 - each major node has its own idea buffer to keep note of specific ideas that I haven't organized yet.
 - at any given point of time, several emtpy nodes may exist : I'm not trying to be exhaustive right away when exploring a domain. This is supposed to be an eternal work in progress. However, to indicate that I intend to work on a node later on and it's not just an empty atom, I've placed ~:tbp:~ (to be populated) tags on such nodes.

* Tag list
Tags are meant to serve as keywords that indicate - at a high level - what a [[id:20230712T211919.917191][buffer]] is about, what phase it is in, and how prominent it is in terms of closeness to a root [[id:20230712T212419.175018][domain]].

** Current tags
**Last Updated** : 0x2172

 - meta
 - tbp
 - ai
 - programming
 - trait
 - nlp
 - math
 - data
 - idealogy
 - python
 - book
 - linguistics
 - lisp
 - cache
 - atomic
 - task
 - posted
 - blog
 - cv
 - root
 - rust
 - web
 - project
 - tool
 - yt
 - nlu
 - java
 - tools
 - cs
 - ml
 - stat
 - prob
 - wip
 - skills
 - writing
 - nn
 - blend
 - transient
 - problem
 - emacs

* Misc

Hi, this is Raj. You've chanced upon my digital note-box (~Zettelkasten) maintained in org-roam. I've circled over a lot of tools to maintain an efficient system in the past and have finally settled on a format that treats everything as text and allows me to spend more time within emacs. I find it difficult to keep track of all that I learn and this dump delegates the notion of remembering to a computer.

I like building connections between domains that are seemingly distinct: I'll be keeping it simple and this note-box will act as an intermediary for the all the [[id:20230712T131112.909632][blogs]] that I intend to regularly push out henceforth. I believe it should be simpler for me to improve my writing skills if I have an informal setup - other than my [[https://rajpatil.dev][main blog]] - where I experiment with varying styles and do not worry about compatibility issues with my existing work.

All of this used to go in my main blog itself around a year ago but things got pretty messy pretty quickly and I myself had trouble indexing all that I'd worked on.

So, I decided to have an explicit clean side and an explicit dirty side that capture my online presence and allow me enjoy the best of both worlds. I wouldn't say I put on a facade on the main blog but it is more curated than whatever goes here. I might even write something down and forget about only to rediscover it again after hundreds of days.

Now that I've used some fillers to separate the casual by-passers ..., 

If you're still reading this, you're a stalker and congrats - you've hit the jackpot. I write about my deepest thoughts and shallowest musings in here and you could form a fairly extensive opinion about my personality and my interests from this dump. Do remember that this still is the tip of the ice berg and apart from the large chunk of information I haven't consolidated about myself, I still consciously choose not to share several other major aspects of my life.

If you're actually reading this, I think we should get to know each other : It's only fair I know a little about you as well... 

I'm most reachable on [[https://twitter.com/rajpatil152k][twitter/x]] and would be glad to connect with like-minded humans and epistemological opposites alike.
