:PROPERTIES:
:ID:       1729
:END:
#+title: Index

* Global Disclaimer
What I compile in these notes isn't meant to be a factual state of the art but how I currently perceive whatever I've partially captured in them.

Expect [[id:be99b67e-e454-4f19-ade7-4c3faf10ce07][paradoxes]], inaccuracies, [[id:d3617afa-85ce-4ac8-bdc3-19fe587c1956][pseudoscience]] and some occasional epiphanies. It's mostly rambling but that is necessary for the rare insight that brings calm to the chaotic combination of concepts that are a prerequisite for a fertile [[id:fef55c48-87a6-4828-a298-4326264fc0e5][Mind]].

I also consider deliberately intellectually [[id:f3347380-f482-4077-a89b-a3ff059b4af6][hallucinating]] so that I can churn up [[id:5a68c46a-85bf-49f1-a589-5a6116f839fb][reality]] a little to chance upon the silver linings that help one push abstract boundaries.

* Endpoints
** [[id:1729][Index]]
 - notes down some basic rules about the braindump's usage
 - stream of generic comments pertaining to the overall logs
** [[id:20230815T212630.336328][questions]]
** [[id:7382d50f-a0aa-4370-baa9-83bb39ccbe1a][resonant-with]]
 - an collection of ideas that I'm resonant with and would like to cache to remind myself of again, sometime down the lane.
** [[id:20230718T222456.978981][input-queue]]
 - an index of resources that I want to consume sometime down the lane
 - anytime I feel like I wish to learn something, I visit this node and populated the buffer accordingly as I learn new skills and accumulate info
** [[id:296b118e-ff24-4423-b343-eb5160102095][work-setup]]
 - a stream of updates pertaining to my physical and cyber work environment
   - might even include updates for mindset changes tending to how I approach work.
** [[id:20231112T080937.669416][Projects]]
 - a cache for ideas that may never see the light of day again.
   - or they just might...
** [[id:20230712T131112.909632][blog]]
 - log of all blogs that  I write down and relevant notes for future works
** [[id:20230727T192932.286062][Youtube]]
 - log of all videos along with plans and indices into drafts
* Stream
** 0x21E0
 - have started using neovim for my programming endeavours
 - still write in gcc emacs and now have a distinct mindset for when I write and when I program
 - I feel that's better than trying to fit everything into one tool.
 - my full-time in emacs wasn't a waste and I've picked up on several useful habits.
 - neovim just seems to be better at cutting through the fluff and is more tailored towards environments I usually work in (remote shells).
** 0x21B1
 - when discussing domains and talking about their overlap, I can qualitatitively judge the closeness of two domains by a metric I picked from my days when I worked in the domain of semantic Segmentation.
 - enter : [[id:e6c6918c-25bd-47f4-830a-4221452885e8][Intersection Over Union]]
 - I'm feeling pretty confident about introducing abstract, partially ordered relations between domains:
   - is a step towards building the [[id:825d36cc-4e03-48e5-bca8-0845e51090af][The Meta-Subject]] 
** 0x21A3
 - getting into the idea of intellectually rambling on the internet
 - I explore something of immediate intrigue and try to update the current state of the dump according to what I consume.
 - a few blurry rules that'll help me not [[id:f3347380-f482-4077-a89b-a3ff059b4af6][hallucinate]] more than I can handle:
   - no resource links to be inserted during such sessions -> wikipedia is a cheatcode only to be used for factual notes
   - all that is inserted needs to be typed in
   - be precise: prune freely, add carefully.
   - verbosity is to be reserved for streams such as this
   - no work related stuff : explore something from a completely different domain
   - a question can serve as a seed for the session but refrain from using the internet right away. Only do so to refine your thought.
 - for today's session, I'm considering talking about meditation: have been regular for 2 weeks for atleast 20 mins a day - somedays are 40 mins long.
   - and I have some interesting thoughts about the "mind" and the nature of the "I".
   - minimizing prior assumptions that aren't well rooted in experiences, off I go ...
** 0x219D
 - careless parenting:
   - henceforth, In these nodes, I'll refrain from making the parent refer the child nodes.
   - the child will be pointing back to the root node instead.
   - that isn't ideal for textual navigation but is sufficient and when using a Graph like Org-roam-ui to visualize the nodes
   - this calls for some pruning : will need to schedule quite a session to actually enforce these regulations so that the network isn't unnecessarily crowded with two way links.
 - Now that I've shifted to neovim for work, only all of my writing and note-taking happens in emacs (+ lisp) so I guess I'm slowly learning to set healthy boundaries in my relationships now.
 - I changed my mind:
   - only the parent logs abstract comments about the child and the child doesn't refer the parent explicitly with "rooted at ..." unnecessary appendices
   - will need to prune the sh*t (I don't know why I'm censoring) out of this someday now.
   - careless children are the way to go.
** 0x2196
 - will be actively populating and pruning the zettelkasten a little more often henceforth.
 - really dialling down into the writer's persona : let's find out what's on my mind and is any of it really worth anything...
 - It will be a mix of writing and research and throwing pointed questions toward the internet to build a more intricate knowledge network over time.
   - I'm hoping this will help me generate a lot of ideas for writing : for AI, lisp and epistemology in general
   - I find a formal reading of a textbook to be a completely different than what I'm going to do for a while.
 - LFG....
** 0x2195
 - contrary to conventional advice, I'm trying to read less than I usually do. On the contrary, I'll be writing more often and be spending more time with my own abstract concoctions. I have noticed that when I'm on a lean intellectual intake or even abstractually(this isn't a word) fasting, I'm creating a lot more and much more original stuff that isn't your run of the mill wanna be writer. Irrespective of the meta-qualitative-aspects of the excerpts and videos I pump out, the sense of satisfaction that I experience when I publish is much more important than the robotic feeling when I produce conventional chunks.
 - I will however be continuing to read works that call for an action and will help me in my immediate pursuits - be that fitness or technical domain expertise.
** 0x2173
 - so, I'm finally done pruning some nodes that weren't serving any purpose.
 - I've also stabilized in my org-mode GTD workflow and find checking tasks off to a be oddly rewarding.
 - It's much better than doing what's more important at the moment.
 - Also working on creating deadlines for me and sticking to them.
 - planning for relaxation is something that I've started doing recently and not caring about work for a definite chunk of the day is worth it.
 - I do seem to have accumulated some writing inertia and considering my brain dump, the main blog and actual work, I've been experiencing fatigued fingers at the end of my workday, almost daily.
 - Also getting back to elevating my typing speed after 5 years.
 - I practiced then and reached upto 100 wpm without punctuations, capitals and numbers.
 - I've sustained it and typing is never a bottleneck
 - Now, I'm adding punctuations, capitals and numbers to my practice sessions (15 mins daily) and am targeting around 150 wpm
   - that is around 12.5 cps (characters per second) - shifting the unit cause this has a nice ring to it.
   - as expected, my speed with all the additions now is around 5 cps
   - deliberately working with harder lessons (unexpected combinations as well) : akin to living with ankle, wrist and torso loads.
 - I think I might start meditating again.
   - I go through cycles of enchantment and boredom in terms of my views for the same but I've noticed it does really help with focus.
   - I usually fit in a 10 min session post workout, pre breakfast and find that my day is more structured and I'm able to get more done on these days.
** 0x2172
 - finally getting around to organizing stuff a little and laying some ground rules
** 0x216A
 - will be cleaning up nodes soon, probably today evening
 - do need a proper place to index the status of some major trees
   - mostly divided in sections like WIP, matured and so on..
 - experiencing stable levels of focus in sessions and the L-tyrosine and good sleep cycles seem to be doing their job well.
 - did chalk out several ideas yesterday on a techno post shower night walk
   - a lot of them are actionable and can be used in the kind of content I'd like to create
** 0x215F
 - need to have a pruning session sometime - a lot of unnecessary nodes that could be better restructured as sub-trees.
 - some nodes are just plain useless and are an itch I scratched gone itchier.
** 0x2154
 - an explicit :wip: tag denotes that I'm actively working on that node (different from :transient:)
** 0x2138
 - the [[id:20230812T200515.697950][literate programming]] setup is live and working well with the publishing script.
 - I have it setup for rust, common lisp and elisp for now
 - mermaid-cli also works for flowcharts locally but need to figure out the publishing process for it to be rendered properly on the online buffer -> UPDATE (2 mins after I pushed this) : just needed to put in an ~exports: both~ in the src blocks..
 - making notes is second nature to me now -> whenever I'm studying/want to start a new project, I don't have to think much in terms of how I'll document the process. The snowball is rolling.
 - Noticing an significant decrease in the pre-thought of remembering stuff before I get start with a domain. Now that it is delegated to something with the memory of a steel trap, all that I learn is a few keystrokes away.
   - surprisingly, I have a mental parallel of this web that I implicitly call upon when remebering stuff -> that is an unexpected and beautiful side-effect...
 - Errors may creep in aynwehr -> I do'nt particurlayl edti what I wirte here and  all is typed in a single pass, along with my thoughts.
   - this might result in needlessly long structures that could be better organized. Of course, I don't do this for the main blog. The buffer is not something that I maintain for perfectionism, but for maintaining a playful approach towards my studies.
** 0x2118
Here are some conventions that I follow to organize my work:
 - [[id:20230712T132110.496747][Timestamps]]
 - will be expressing math as [[id:20230712T223044.319985][S-expressions]] rather than latex
   - the former flow fluidly off my fingers
   - the latter I'll reserve when for publishing on the main blog: latex isn't exactly good while note taking - is a distraction.
   - my goal being encoding the concept (procedure/definition/relation) in a way that is more accessible to that of a programmer's mind
   - I also choose to do so as it'll help me learn map concepts from different domains into a common symbolic representation (hmmmm ... : yeah...., math already does that - I guess I'm just being peevish)
 - A top-down knowledge building style : the human mind doesn't remember what it knows. Trying to remember a specific latent knowledge node in this graph will be more efficient than building all the base nodes one by one until I reach a practical level of application. I will add atoms as and when I see fit : I might even insert most from memory.
 - each major node has its own idea buffer to keep note of specific ideas that I haven't organized yet.
 - at any given point of time, several emtpy nodes may exist : I'm not trying to be exhaustive right away when exploring a domain. This is supposed to be an eternal work in progress. However, to indicate that I intend to work on a node later on and it's not just an empty atom, I've placed ~:tbp:~ (to be populated) tags on such nodes.

 Tag list
Tags are meant to serve as keywords that indicate - at a high level - what a [[id:20230712T211919.917191][buffer]] is about, what phase it is in, and how prominent it is in terms of closeness to a root [[id:20230712T212419.175018][domain]].

* Current tags
**Last Updated** : 0x21E0
 - tbp
 - stat
 - prob
 - math
 - meta
 - nlp
 - emacs
 - ai
 - ml
 - cv
 - tool
 - root
 - transient
 - trait
 - lisp
 - nn
 - skills
 - project
 - programming
 - biology
 - python
 - cs
 - pseudoscience
 - cache
 - rust
 - AI
 - org
 - vim
 - yt
 - tools
 - atomic
 - computer
 - web
 - diff
 - data
 - Categories
 - java
 - writing
 - metric
 - book
 - task
 - wip
 - blog
 - problem
 - nlu
 - blend
 - posted
 - physics
 - logic
 - idealogy
 - psych
 - society
 - electronics
 - linguistics
