name: Publish
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Org Roam Publish
        uses: maker2413/OrgRoamPublish@v1.0.1
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2 
