name: org roam ui publish
on:
  push:
    branches:
      - org-roam-ui
      
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: yarn

      - name: Open workspace
        run: cd publish-ui
          
      - name: Install Dependencies
        run: yarn
        
      - name: Build
        run: yarn build
        
      - name: Export
        run: yarn export
        
      - name: add nojekyll
        run: touch out/.nojekyll

      - name: Return to root
        run: cd ..
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: publish-ui/out
