name: org roam ui publish
on:
  push:
    branches:
      - org-roam-ui
      
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: yarn

#       - name: Install Dependencies
#         run: yarn install
        
#       - name: Build
#         run: yarn run build
        
#       - name: Export
#         run: yarn run export
      - name: modify exec permissions
        run: chmod +x ./standalone/build-standalone-server.sh

      - name: build files
        run: ./build-standalone-server.sh ./Content
        shell: bash
        working-directory: ./standalone
      
      - name: add nojekyll
        run: touch ./out/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
