name: Publish
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Publish Org Files
      uses: maker2413/OrgRoamPublish@v1.0.0
