name: Publish

on:
  push:
    branches:
      - master
  workflow_run:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Org Roam Publish
        uses: maker2413/OrgRoamPublish@v1.0.1
        with:
          publish_script: publish.el
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './_site'
          
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v2.0.3
